services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: swequizzes
      POSTGRES_USER: swequizzes
      POSTGRES_PASSWORD: swequizzes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
