spring.datasource.url=jdbc:postgresql://localhost:5432/swequizzes
spring.datasource.username=swequizzes
spring.datasource.password=swequizzes

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
